// src/App.tsx
import { Col, Row, Space, Typography } from 'antd';
import { aboutTabs, portfolioItems, skills } from './data/content';
import { AboutTabs } from './components/AboutTabs';
import { PortfolioCard } from './components/PortfolioCard';
import { SiteHeader } from './components/SiteHeader';
import { SkillCard } from './components/SkillCard';
import './App.css';

const { Title, Paragraph } = Typography;

export default function App() {
  return (
    <>
      <SiteHeader />

      <aside className="sl-jumbotron mb-0">
        <div className="site-container flex h-full flex-col justify-center pt-5 pb-5">
          <Space orientation="vertical" size="middle" className="w-full">
            <Title level={1} className="display-3 pt-3 !mb-0 !text-inherit">
              Hi! I&apos;m Sean Loyless,
            </Title>
            <Paragraph className="display-4 fw-bolder text-danger !mb-0">
              Application Engineer
            </Paragraph>
            <Paragraph className="display-4 !mb-0 pb-3">in NYC.</Paragraph>
          </Space>
        </div>
      </aside>

      <main>
        <section id="about" className="site-container my-5">
          <Row gutter={[24, 24]} align="top">
            <Col xs={24} md={8}>
              <img
                src="/assets/images/about.jpg"
                alt=""
                className="about-photo w-full"
              />
            </Col>
            <Col xs={24} md={16} className="md:!pl-12">
              <Space
                orientation="vertical"
                size="middle"
                className="w-full items-start"
              >
                <Title level={2} className="display-5 !mb-0">
                  About Me
                </Title>
                <Space orientation="vertical" size="middle">
                  <Paragraph className="lead !mb-0">
                    I&apos;ve been programming since I was 11 years old! I spent
                    hours in front of my Atari XL-800 learning BASIC programming
                    from the back of <em>3-2-1 Contact</em> magazines.
                  </Paragraph>
                  <Paragraph className="!mb-0">
                    I love the challenge of programming with the constant
                    learning required to stay on top of the latest technologies
                    and trends to support my clients.
                  </Paragraph>
                </Space>
                <AboutTabs tabs={aboutTabs} />
              </Space>
            </Col>
          </Row>
        </section>

        <section id="skills" className="pb-5">
          <div className="skills-inner site-container text-light">
            <Space
              orientation="vertical"
              size="middle"
              className="mb-4 w-full pt-5"
            >
              <Title level={2} className="display-4 !mb-0 text-center">
                My Toolbox
              </Title>
              <Paragraph className="lead !mb-0 text-center">
                These are just a few of the skills I use everyday as a developer.
              </Paragraph>
            </Space>
            <Row gutter={[24, 24]} className="mb-4">
              {skills.map((skill) => (
                <Col key={skill.title} xs={24} md={8}>
                  <SkillCard skill={skill} />
                </Col>
              ))}
            </Row>
          </div>
        </section>

        <section id="portfolio" className="py-5">
          <div className="site-container text-light">
            <Space orientation="vertical" size="middle" className="mb-4 w-full">
              <Title level={2} className="display-4 !mb-0 text-center">
                Portfolio
              </Title>
              <Paragraph className="lead !mb-0 text-center">
                A few of the clients I have done work for over my career.
              </Paragraph>
            </Space>
            <Row gutter={[24, 24]} className="mb-4">
              {portfolioItems.map((item) => (
                <Col key={item.id} xs={24} md={8}>
                  <PortfolioCard item={item} />
                </Col>
              ))}
            </Row>
          </div>
        </section>
      </main>
    </>
  );
}

// src/app/app.component.ts
import { Component } from '@angular/core';
import { AboutTabs, Skill, PortfolioCard } from './app.models';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'Portfolio of Sean Loyless';
  aboutActive = 1;

  readonly items: AboutTabs[] = [
    {
      id: 1,
      title: 'Top Skills',
      detail: [
        {
          title: 'Full Stack/Application Developer',
          subtitle: 'Development',
          text: 'Over 20 years of professional programming experience in website and mobile app development.'
        },
        {
          title: 'Application Architecture',
          subtitle: 'UX/UX',
          text: 'Enterprise, large scale applications, and design system planning and development.'
        },
        {
          title: 'Lead Developer Roles',
          subtitle: 'Leadership',
          text: 'Able to manage small and large teams of local and offshore developers to meet project goals.'
        },
        {
          title: 'Accessibility and Responsive Design',
          subtitle: 'a11y',
          text: 'Supporting a11y standards and mobile-first design in all projects from the start.'
        },
      ]
    },
    {
      id: 2,
      title: 'Awards',
      detail: [
        {
          title: 'Winner of IBM Hackathon Challenge',
          subtitle: '48in48',
          text: 'Participated in the October 2020 48in48 Hackathon challenge supporting Black-owned charities.'
        },
        {
          title: 'Financial Innovation Awards',
          subtitle: 'Digital Evolution Program',
          text: 'San Antonio Chamber of Commerce website'
        }
      ]
    },
    {
      id: 3,
      title: 'Experience',
      detail: [
        {
          title: 'Application Developer',
          subtitle: 'IBM Consulting - iX',
          text: '2016 - Current'
        },
        {
          title: 'Presentation Layer Engineer',
          subtitle: 'Razorfish',
          text: '2012 - 2016'
        }
      ]
    },
    {
      id: 4,
      title: 'Education',
      detail: [
        {
          title: 'Art Institute of Houston',
          subtitle: 'Associate of Science - Multimedia',
          text: '2001'
        },
        {
          title: 'Magnolia High School',
          subtitle: 'Magnolia, TX',
          text: '1996'
        }
      ]
    },
  ];

  readonly skills: Skill[] = [
    {
      title: 'Website Development',
      icon: 'bi-code-square',
      text: 'Full-stack programming and markup including HTML, SCSS/CSS, JavaScript, Angular, React, PHP, MySQL.'
    },
    {
      title: 'Graphic Design',
      icon: 'bi-images',
      text: 'I spent the beginning of my career (2001-2005) as a Graphic Designer before moving into web development, which has served me well in working with other designers.'
    },
    {
      title: 'Mobile App Development',
      icon: 'bi-phone-vibrate',
      text: 'Creating cross-platform mobile applications in React Native.'
    },
    {
      title: 'Application Architecture',
      icon: 'bi-server',
      text: 'Create Enterprise-level website or mobile applications from top to bottom. Scoping, discovery, and design systems.'
    },
    {
      title: 'Accessibility First',
      icon: 'bi-eye',
      text: 'Every site or application I build has heavy consideration on a11y requirements for people with visual disabilities.'
    },
    {
      title: 'Marketing & Reporting',
      icon: 'bi-bar-chart-line',
      text: 'Experience with Analytics and reporting tools.'
    },
  ]

  readonly portfolioItems: PortfolioCard[] = [
    {
      id: 202010,
      date: '2020',
      title: 'United Cargo',
      client: 'IBM iX',
      image: '/assets/portfolio/unitedcargo.jpg',
    },
    {
      id: 202003,
      date: '2020',
      title: 'Kichler Lighting',
      client: 'IBM iX',
      image: '/assets/portfolio/kichler.jpg',
    },
    {
      id: 201807,
      date: '2018',
      title: 'P-TECH Academy',
      client: 'IBM iX',
      image: '/assets/portfolio/ptech.jpg',
    },
    {
      id: 201803,
      date: '2018',
      title: 'Childrens Defense Fund',
      client: 'IBM iX',
      image: '/assets/portfolio/cdf.jpg',
    },
    {
      id: 201707,
      date: '2017',
      title: 'United Airlines',
      client: 'IBM iX',
      image: '/assets/portfolio/united.jpg',
    },
    {
      id: 201504,
      date: '2015',
      title: 'AT&T Small Business',
      client: 'Razorfish',
      image: '/assets/portfolio/attcircle.jpg',
    },
    {
      id: 201404,
      date: '2013',
      title: 'Blackberry',
      client: 'Razorfish',
      image: '/assets/portfolio/blackberry.jpg',
    },
  ]
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
  <div class="container">
    <a class="navbar-brand" href="/" title="The Portfolio of Sean Loyless">
      <img src="/assets/images/logo-notag.svg" alt="" class="d-inline-block align-text-top" height="45">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#skills">Skills</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#portfolio">Portfolio</a>
        </li>
      </ul>
    </div>
    <ul class="navbar-nav d-none d-md-flex">
      <li class="nav-item">
        <a class="nav-link fs-4" href="https://github.com/sloyless" target="_blank" title="Github profile of Sean Loyless"><i class="bi bi-github"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link fs-4" href="https://www.linkedin.com/in/seanloyless/" target="_blank" title="LinkedIn profile of Sean Loyless"><i class="bi bi-linkedin"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link fs-4" href="https://twitter.com/crudebaron/" target="_blank" title="Twitter profile of Sean Loyless"><i class="bi bi-twitter"></i></a>
      </li>
    </ul>
  </div>
</nav>
<aside class="jumbotron jumbotron-fluid mb-0 text-light pt-5 pb-5 sl-jumbotron">
  <div class="container pt-5 pb-5">
    <h1 class="display-3 pt-3">Hi! I'm Sean Loyless,</h1>
    <p class="display-4 fw-bolder mb-3 text-danger">Application Developer</p>
    <p class="display-4 pb-3">in NYC.</p>
  </div>
</aside>
<main>
  <section class="mt-5 mb-5 container" id="about" name="about">
    <div class="row">
      <div class="col-md-4 mb-3 mb-md-0">
        <img src="/assets/images/about.jpg" alt="" class="img-fluid rounded shadow" />
      </div>
      <div class="col-md-8 ps-md-5">
        <h2 class="display-5">About Me</h2>
        <p class="lead">I've been programming since I was 11 years old! I spent hours in front
          of my Atari XL-800 learning BASIC programming from the back of <em>3-2-1 Contact</em>
          magazines.</p>
        <p>I love the challenge of programming with the constant learning required to
          stay on top of the latest technologies and trends to support my clients.
        </p>
        <ul ngbNav #nav="ngbNav" [(activeId)]="aboutActive" class="nav-tabs border-0">
          <li *ngFor="let item of items;" [ngbNavItem]="item.id">
            <a ngbNavLink class="bg-transparent fw-bold pt-0 pb-1 px-0">{{item.title}}</a>
            <ng-template ngbNavContent>
              <skill-tab-item [item]="item"></skill-tab-item>
            </ng-template>
          </li>
        </ul>
        <div [ngbNavOutlet]="nav" class="mt-2"></div>
      </div>
    </div>
  </section>
  <section id="skills" name="skills" class="pb-5">
    <div class="container text-light">
      <h2 class="pt-5 mb-0 text-center display-4">My Toolbox</h2>
      <p class="lead text-center mb-4">These are just a few of the skills I use everyday as a developer.</p>
      <div class="row row-cols-1 row-cols-md-3 g-4 mb-4">
        <div *ngFor="let skill of skills" class="col">
          <skill-card [skill]="skill"></skill-card>
        </div>
      </div>
    </div>
  </section>
  <section id="portfolio" name="portfolio" class="pt-5 pb-5">
    <div class="container">
      <h2 class="mb-0 display-4 text-center">Portfolio</h2>
      <p class="lead text-center">A few of the clients I have done work for over my career.</p>
      <div class="row row-cols-1 row-cols-md-3 g-4 mb-4">
        <div class="col" *ngFor="let item of portfolioItems">
          <portfolio-card [item]="item"></portfolio-card>
        </div>
      </div>
    </div>
  </section>
</main>
